<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CortexFlow.Core\CortexFlow.Core.csproj" />
    <ProjectReference Include="..\CortexFlow.Infrastructure\CortexFlow.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF.UI" Version="3.4.2.7" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
